### PR TITLE
My previous issues

### PR DESCRIPTION
**Pull request by gabriellemrs16**
Here are the previous fixes I originally did that didn't get merged :)
I am still trying to figure out the ddl and autocomplete

### CODE REVIEW

**Comment by abaporu-C** [comment]
Sorry, It is not working. 

I can't create a new order because the CreateOrder modal does not work.

**Comment by gabriellemrs16** [comment]
Yeah sorry, I forgot about that. Are you able to merge everything BUT the create order modal? Or would you rather me finish the modal, then merge?

**Comment by abaporu-C** [comment]
I would much rather you finish your modal. 

There is one other thing as well, make sure you make your tables consistent through Create, Edit and Detail Order Views.

**Comment by gabriellemrs16** [comment]
Ah okay. Is that why you didn't merge them last time? Cause the tables are different?

**Comment by abaporu-C** [comment]
Actually no. I remember that I edit your branch to make them look the same, but I got lost on the merge. Sorry about that :/.

**Comment by gabriellemrs16** [comment]
It's all good Vin! I'll change them to make them look the same when I get home later today :)

**Comment by gabriellemrs16** [comment]
Hey Vin! My order tables look the exact same to me compared to the published site. Idk what is different. I'll fix it tho if you point it out :) Thanks!

**Comment by abaporu-C** [comment]
Awesome!

Is the Create Order modal working?

**Comment by gabriellemrs16** [comment]
It is not, but I'll be working on that today. I'm ngl, I'm completely stumped on it. I think I'm really close to figuring it out, but I'm not sure what I'm doing wrong 😭 I've watched Dave's lecture on it and I'm fairly certain all my code is correct. Any help would be greatly appreciated! (Not just from you, from everyone, but I know today is Easter so no worries and Happy Easter!)

**Comment by abaporu-C** [comment]
I can see if I can figure it out later today.

I manage to close a good amount of issues this morning. I'll work on that at night and publish everything to azure.

**Comment by gabriellemrs16** [comment]
Omg you God. Tysm. I'll try and do a different issue then :)

**Comment by abaporu-C** [comment]
Closed with pull request #343

**Pull request closed without merging**
